version: "3.7"
services:
  mynode:
    image: prom/node-exporter:latest
    container_name: "node0"
    ports:
      - "9100:9100"
      - "8080:8080"
    volumes:
      - "./program:/home"
    restart: always
    command:
      - '--collector.processes'
  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus0"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: "grafana0"
    ports:
      - "3000:3000"
    restart: always


