version: "3.7"
services:
  mynode:
    image: prom/node-exporter:latest
    container_name: "node0"
    ports:
      - "9100:9100"
      - "8080:8080"
      - "8090:8090"
    volumes:
      - "./program:/program"
      - "./logs:/logs"
    restart: always
    entrypoint: "sh /program/start_node_exporter.sh"


  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus0"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: "grafana0"
    ports:
      - "3000:3000"
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.2
    container_name: filebeat
    user: root
    volumes:
      - ./logs:/logs
      - ./logconf:/logconf
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: filebeat -e -d "*"
    depends_on:
      - elasticsearch
      - logstash

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    mem_reservation: 1000M
    cpu_count: 1
  ubuntu:
    image: ubuntu
    command: ./webhookserver
    ports:
      - "16060:16060"
    volumes:
      - "./program:/program"
    working_dir: /program

