max_bytes: 3145728
max_procs: 1
#setup.template.name: "filebeat"
#setup.template.pattern: "filebeat-*"
#setup.ilm.enabled: false
filebeat.config.inputs:
  enabled: true
  path: /logconf/*.yml

output.logstash:
  hosts: ["logstash:5044"]

#output.elasticsearch:
#  hosts: [ "http://192.168.17.150:9200" ]
#  index: "filebeat-%{[fields.log_type]}-%{+yyyy.MM.dd}"
#
#setup.kibana:
#  host: "http://192.168.17.150:5601"
#setup.template.enabled: true
logging.level: info
logging.to_files: true
logging.files:
  path: /logs/filebeat
  name: filebeat
  keepfiles: 7