global:
  scrape_interval:     15s # 默认抓取周期
scrape_configs:
  - job_name: 'normal'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['mynode:9100']

  - job_name: 'webapp'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'mynode:8090' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: instance
        regex: (.*):\d+
        replacement: $1