{
 "title": "应用服务",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(server_handle_seconds_bucket,job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(server_handle_seconds_bucket,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$app\",instance=~\"$node\"}[3m])"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$app\",instance=~\"$node\"}",
     "legendFormat": "{{instance}},{{job}}"
    }
   ]
  },
  {
   "title": "go sched lantercy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999,sum by (le,instance,job) (rate(go_sched_latencies_seconds_bucket{job=~\"$app\",instance=\"$node\"}[1m])))",
     "legendFormat": "{{instance}},{{job}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$app\",instance=~\"$node\"}",
     "legendFormat": "{{instance}},{{job}}"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$app\",quantile=~\"1|0.75\",instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(server_handle_seconds_bucket{type=\"http\",job=~\"$app\",instance=~\"$node\"}[5m])) by (le,api,method))"
    }
   ]
  },
  {
   "title": "qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(irate(server_handle_seconds_count{type=\"http\",job=~\"$app\",instance=~\"$node\"}[5m])) by (api,method)"
    }
   ]
  },
  {
   "title": "错误数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(server_handle_seconds_sum{type=\"http\",status !=\"200\",job=~\"$app\",instance=~\"$node\"}[5m])) by (api,method)"
    }
   ]
  }
 ]
}