{
 "title": "redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(client_handle_total{type='redis'},job)"
    }
   },
   {
    "name": "op",
    "query": {
     "query": "label_values(client_handle_total{type='redis'},op)"
    }
   },
   {
    "name": "cachename",
    "query": {
     "query": "label_values(client_handle_total{type='redis'},peer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "qps by key",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(client_handle_total{job=~\"$app\",op=~\"$op\",peer=\"$cachename\"}[5m])) by (name)"
    }
   ]
  },
  {
   "title": "crud qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(client_handle_total{job=~\"$app\",type=\"redis\",peer=\"$cachename\"}[5m])) by (job,op)"
    }
   ]
  },
  {
   "title": "qps by app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(client_handle_total{job=~\"$app\",type=\"redis\",peer=\"$cachename\"}[5m])) by (job)"
    }
   ]
  }
 ]
}