{
 "title": "instances",
 "tags": [ "linux" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  { "title": "CPU / Mem / Network / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 } },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Traffic by Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 } },
  {
   "title": "Process / TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_procs_blocked{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Processes in runnable state"
      }
     ]
    },
    {
     "title": "Processes State",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_processes_state{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ state }}"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "CurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "MaxConn - Limit on the total number of TCP connections the entity can support (Dynamic is \"-1\")"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenOverflows - Times the listen queue of a socket overflowed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ListenDrops - SYNs to LISTEN sockets ignored"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCPSynRetrans - SYN-SYN/ACK retransmits to break down retransmissions in SYN, fast/timeout retransmits"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RetransSegs - Segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "InErrs - Segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OutRsts - Segments sent with RST flag"
      }
     ]
    },
    { "title": "Network Traffic Errors", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 } },
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Transmit drop"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resource Limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NF Contrack",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NF conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NF conntrack limit"
    }
   ]
  },
  {
   "title": "Threads Number and Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Allocated threads"
    },
    {
     "expr": "node_processes_max_threads{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Threads limit"
    }
   ]
  },
  {
   "title": "PIDs Number and Limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_pids{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Number of PIDs"
    },
    {
     "expr": "node_processes_max_processes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PIDs limit"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max open files"
    },
    {
     "expr": "node_filefd_allocated{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "Network Traffic Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Receive errors"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Rransmit errors"
    }
   ]
  }
 ]
}